version: 2.1
jobs:
  build:
    docker:
     - image: cimg/python:3.11.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          comand: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest test.py



  